name: carehome
description: "carehome-nerse"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  animated_custom_dropdown: ^3.1.1
  shared_preferences: ^2.5.4
  dartz: ^0.10.1
  http: ^1.6.0
  dio: ^5.9.0
  geocoding: ^4.0.0
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/mock/
